services:
  rabbitmq:
    hostname: 'dev-rabbitmq' 
    image: rabbitmq:3-management
    container_name: 'project-rabbitmq'
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
    networks:
            - test-network

networks:
    test-network:
        driver: bridge 